// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jVxwFGWcXf_5WFMopckD6Q2nTHVfxBI',
    appId: '1:730565006517:web:4cfacdd29dcf484fc55afc',
    messagingSenderId: '730565006517',
    projectId: 'depremdayanisma-e208a',
    authDomain: 'depremdayanisma-e208a.firebaseapp.com',
    storageBucket: 'depremdayanisma-e208a.appspot.com',
    measurementId: 'G-6F9PMBXT8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAPvXBjehfDxOC4FQNPGBHlm6iBmf_vM',
    appId: '1:730565006517:android:4691248fc1cbc216c55afc',
    messagingSenderId: '730565006517',
    projectId: 'depremdayanisma-e208a',
    storageBucket: 'depremdayanisma-e208a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW0I2ProP2FqiIgPFs08jmjaBf74nMslw',
    appId: '1:730565006517:ios:b7f93e2f1108a584c55afc',
    messagingSenderId: '730565006517',
    projectId: 'depremdayanisma-e208a',
    storageBucket: 'depremdayanisma-e208a.appspot.com',
    iosBundleId: 'com.example.farukhelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW0I2ProP2FqiIgPFs08jmjaBf74nMslw',
    appId: '1:730565006517:ios:b7f93e2f1108a584c55afc',
    messagingSenderId: '730565006517',
    projectId: 'depremdayanisma-e208a',
    storageBucket: 'depremdayanisma-e208a.appspot.com',
    iosBundleId: 'com.example.farukhelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-jVxwFGWcXf_5WFMopckD6Q2nTHVfxBI',
    appId: '1:730565006517:web:c702fdbffed61b58c55afc',
    messagingSenderId: '730565006517',
    projectId: 'depremdayanisma-e208a',
    authDomain: 'depremdayanisma-e208a.firebaseapp.com',
    storageBucket: 'depremdayanisma-e208a.appspot.com',
    measurementId: 'G-HNBGWTQG72',
  );

}